name: 构建项目并且推送到dockerhub

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: 构建项目
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: 登录DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: 构建并推送Docker镜像
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: zhanzk/drink_water_helper:latest
